### ISSUE TITLE
[Q] I am lost on how i should get the arrivals to display on the front end

### ISSUE THREAD

**Issue by jorhden** [ADES-FSP/2122s1-CA1#2]
| field | value | example|
| - | - | - |
| Name | Jorden Hang | Jeremiah Ang (As in MS Teams) |
| Class | 2B/24 | 2B/21 |

> Replace `????` with your name and class

**Describe the bug/question/problem you faced**

On the browser side, when i click on send request for stats/arrivals it does not show me anything on the front end website charts

Only when i send request for /afjsdlfjsdl it shows me bars on both charts when it should only be for the error chart

![image](https://user-images.githubusercontent.com/82923619/118452292-96b5be00-b728-11eb-8497-88f5a3377bf8.png)

i have tried to log out some text to check whether the arrivals endpoint is being called and the text is only logged out in the vscode terminal and not the browser console
![image](https://user-images.githubusercontent.com/82923619/118452406-b220c900-b728-11eb-8e83-043d63101676.png)

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

I expected that sending request for the stats/arrivals endpoint will display it on the front end chart with a green bar

**Screenshots**
If applicable, add screenshots to help explain your problem. Some screenshots you may want to add:
1. All the information about the HTTP request you’re making (e.g. the method, the path, the query, the body, etc…)
2. The response you are getting from the backend.
    1. For website: go to Inspect > Network > Click on request > Response.
3. Your init.sql
4. The complete error message you received

**Additional context**
Add any other context about the problem here. (e.g. using elephantSql instead of Docker)

**Comment by jeremiah-ang** [comment]
As per the call, 

From the `Network` tab, we saw that request were only made to `/errors` endpoint and not to `/arrivals`

We later inspected to see that you were actually only exporting `getErrorsPayload` from `./connector` instead of both `getErrorsPayload` and `getArrivalsPayload`. 

You had to make 2 changes to fix the import and export 

1. in `./connector.mjs`, you had to remove the `default` keyword. and 
2. in `./charts.mjs`, you had to change the import to:
    ```js
    import { getErrorsPayload, getArrivalsPayload } from `./connector`;
    ```
